version: '3.8'
services:
  bot:
    build: app
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - MODE=${MODE}
      - PORT=${PORT}
      - HF_MODEL_NAME=${HF_MODEL_NAME}
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
  db:
    image: postgres:16.1-bullseye
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "${POSTGRES_CONTAINER_PORT}:${DATABASE_PORT}"

volumes:
  db_data:
