version: '3.9'
services:
  app:
    build: app
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:16.1-bullseye
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "${DB_CONTAINER_PORT}:${DATABASE_PORT}"

volumes:
  db_data:
